config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs do
    post 'confirm', on: :collection
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  
  private
  
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
    
  end

  def create
    @blog = current_user.blogs.build(blog_params) #ログインしているユーザーがブログを作成し、それを@blogに代入
    render :new if params[:back]
    if @blog.save
      redirect_to blogs_path flash[:notice] = "投稿しました!"
    else
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    # @blog = Blog.find(params[:id])
    render :new if @blog.invalid?
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    render :new if params[:back]
    if @blog.update(blog_params)
      redirect_to blogs_path 
    else
      render :new
    end
  end
    
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    if @blog.destroy
      redirect_to blogs_path flash[:notice] = "削除しました!"
    end
  end
  private

  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました。メールアドレスもしくはパスワードが違います。'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<body class="img">
  <%= form_with(model: @blog, url: choose_new_or_edit, local: true) do |form| %>
    <% if @blog.errors.any? %>
    <div class="error_messages">
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
    <% end %>

    <div class="blog">
      <%= form.label :content, "投稿内容", class: "content" %>
      <%= form.text_field :content, class: "text", placeholder: "内容を入力"%>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>

    <%= form.submit%>
    <%= link_to "戻る",  blogs_path%>
  <% end %>
<body>

app/views/blogs/confirm.html.erb
<h3>以下の内容で投稿してもよろしいですか？</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
    <p>投稿内容:<%= @blog.content %></p>
    <p>投稿画像:<%= @blog.image %></p>
  <%= form.submit  "投稿する" %>
<%end%>

<%= form_with(model:@blog, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= link_to "戻る", :back%>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<body class="index">
  <h1 class="title">友達繋がり</h1>
  <table class="table">
      <tr>
        <th>内容</th>
        <th></th>
      </tr>

    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.content %></td>
        <td><%= link_to "詳細の確認", blog_path(blog.id)%>
        <%= link_to "ツイートの編集", edit_blog_path(blog.id), data: {confirm: "本当に編集してもいいですか？"}%>
        <%= link_to "ツイートを削除", blog_path(blog.id),  method: :delete,data: {confirm: "本当に削除してもいいですか？"}%>
        <p>ユーザーネーム:<%= blog.user.name%></p></td>
      </tr>
    <% end %>

    <%= link_to "新しく投稿する", new_blog_path %>
  </table>
</body>

app/views/blogs/new.html.erb
<h1>内容入力画面</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="container">
  <h2>内容</h2>
  <p class="content"><%= @blog.content%></p>

  <p>
    <strong>Image</strong>
    <% if @blog.image? %>
      <%= image_tag @blog.image.url class:"img"%>
    <% else %>
      <p>画像は無し</p>
    <% end %>
  </p>


  <%= link_to "戻る", blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tomodati</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class = "container">
	<div class="wrapper">
		<%= form_with(model: @user, local: true) do |f| %>
		  <h3 class="form-signin-heading">Welcome! Please_SignUp</h3>

		  <hr class="colorgraph"><br>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Name"%>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "Email"%>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password_Confirmation" %>

      <%= f.submit "Create account!", class: "btn btn-lg btn-primary btn-block"%>
    <% end %>				
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>